name: Build Armbian Vontar H618 Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 600

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cache Armbian
      uses: actions/cache@v4
      with:
        path: |
          cache
          output/cache
        key: armbian-cache

    - name: Build Armbian Image
      run: |
        export LC_ALL=C
        export LANG=C
        export DEBIAN_FRONTEND=noninteractive
        
        ./compile.sh kernel \
        BOARD=vontar-h618 \
        BRANCH=current \
        RELEASE=bookworm \
        KERNEL_CONFIGURE=no \
        ARTIFACT_IGNORE_CACHE=yes \
        SKIP_ARTIFACT_CLEANUP=yes
       

    - name: Upload kernel debs
      if: always()   # 即使前一步失败也执行
      uses: actions/upload-artifact@v4
      with:
        name: h618-kernel
        path: output/packages-hashed/*.tar
